### PR TITLE
Upgrade for 2.13 and Dependency Upgrades

### PR DESCRIPTION
**Pull request by ChristopherDavenport**

### CODE REVIEW

**Comment by pchlupacek** [comment]
@ChristopherDavenport  thanks so much for this.

**Comment by ChristopherDavenport** [comment]
This is blocking release of newest upstreams. What can I do to assist moving this forward?

I'd also volunteer as a maintainer if you would take me. This is a critical part of the dependency stack presently as without it we don't have TLS support.

**Comment by pchlupacek** [comment]
@ChristopherDavenport sorry, on it

**Comment by AdamChlupacek** [comment]
@ChristopherDavenport I have just released 0.5.0-M1 which is build against fs2 1.1.0-M1. I have also invited you to be Collaborator, on this repository.

**Pull request merged**
